import type { Review } from "@/types/review";

// Low-signal Facebook comment-thread noise that isn't an actual review
// (order-status pings, one-word bumps) — filtered out automatically below
// so pasting in a fresh batch of raw comments doesn't require hand-picking
// through them first.
const NON_REVIEW_PATTERNS: RegExp[] = [
  /^pm$/i,
  /^repl(y|ies)$/i,
  /^ups?$/i,
  /^mine$/i,
  /^available\??$/i,
  /^h+m+\??$/i,
  /^price\??$/i,
  /^magkano\??$/i,
  /^how\s*much\??$/i,
  /^meron\s*pa\??$/i,
];

// One-word comments are usually thread noise ("Up", "Mine", "Price?") — but
// short one-word vouches ("Legit", "Trusted", "Vouch") are the single most
// common genuine review on this page, so they're kept.
const GENUINE_ONE_WORD = /legit|trust|vouch|solid|recommend|bilis/i;

function isGenuineReview(text: string): boolean {
  const normalized = text.trim();
  if (NON_REVIEW_PATTERNS.some((pattern) => pattern.test(normalized))) {
    return false;
  }

  const words = normalized.replace(/[!?.,]+$/g, "").split(/\s+/);
  if (words.length === 1 && !GENUINE_ONE_WORD.test(words[0])) {
    return false;
  }

  return true;
}

// Sourced from real customer comments on the BudgetWise Facebook vouch post
// (facebook.com/share/p/1Ub2UPFdkv), cleaned up for encoding artifacts and
// trimmed to first names only. Paste in more the same way — isGenuineReview
// above strips out any non-review noise automatically, and the homepage
// carousel and "View more reviews" button both key off the exported
// `reviews` list and need no other changes.
const rawReviews: Review[] = [
  { id: "1", name: "Paul", rating: 5, text: "Legit broooo!", platform: "Facebook" },
  { id: "2", name: "Joaquin", rating: 5, text: "Legit fast transaction!", platform: "Facebook" },
  { id: "3", name: "John", rating: 5, text: "Super l!", platform: "Facebook" },
  { id: "4", name: "James", rating: 5, text: "L! 3rd time!", platform: "Facebook" },
  { id: "5", name: "Tixie", rating: 5, text: "Legit!", platform: "Facebook" },
  { id: "6", name: "Jayem", rating: 5, text: "Legit guys. Quick to talk!", platform: "Facebook" },
  { id: "7", name: "Ethan", rating: 5, text: "Legit smooth transaction thank you po!", platform: "Facebook" },
  { id: "8", name: "Angel", rating: 5, text: "Le is git!", platform: "Facebook" },
  { id: "9", name: "Yuri", rating: 5, text: "Legit!", platform: "Facebook" },
  { id: "10", name: "Simon", rating: 5, text: "LEGIT!", platform: "Facebook" },
  { id: "11", name: "James", rating: 5, text: "Smooth transaction!", platform: "Facebook" },
  { id: "12", name: "Gustavo", rating: 5, text: "BIG LEGIT!", platform: "Facebook" },
  { id: "13", name: "Hendrick", rating: 5, text: "Yah ala reply!", platform: "Facebook" },
  { id: "14", name: "Jhaycee", rating: 5, text: "2nd time purchasing legit and smooth!", platform: "Facebook" },
  { id: "15", name: "Iverson", rating: 5, text: "Super legit, I've been able to avail a lot!", platform: "Facebook" },
  { id: "16", name: "Railey", rating: 5, text: "Legit!", platform: "Facebook" },
  { id: "17", name: "Jay", rating: 5, text: "LEGITTTT!!! PALDOO!", platform: "Facebook" },
  { id: "18", name: "Lucas", rating: 5, text: "Legit!", platform: "Facebook" },
  { id: "19", name: "Joshua", rating: 5, text: "Pa reply pooo!", platform: "Facebook" },
  { id: "20", name: "Roldan", rating: 5, text: "Super Legittttt!", platform: "Facebook" },
  { id: "21", name: "Awin", rating: 5, text: "UP, LEGIT!", platform: "Facebook" },
  { id: "22", name: "Ryan", rating: 5, text: "Legit!", platform: "Facebook" },
  { id: "23", name: "Mhyke", rating: 5, text: "Legit 100%!", platform: "Facebook" },
  { id: "24", name: "Moadz", rating: 5, text: "Legittt W!", platform: "Facebook" },
  { id: "25", name: "Kinglance", rating: 5, text: "Lijett!", platform: "Facebook" },
  { id: "26", name: "Bhong", rating: 5, text: "Super legit po!", platform: "Facebook" },
  { id: "27", name: "Fermin", rating: 5, text: "Legit 100% fast transaction!", platform: "Facebook" },
  { id: "28", name: "Jxhn", rating: 5, text: "Trusted too mennn!", platform: "Facebook" },
  { id: "29", name: "Shawn", rating: 5, text: "LEGIT!", platform: "Facebook" },
  { id: "30", name: "Ryan", rating: 5, text: "5th transact, thank u BW!", platform: "Facebook" },
  { id: "31", name: "Shun", rating: 5, text: "LEGIT SUPER!", platform: "Facebook" },
  { id: "32", name: "Clark", rating: 5, text: "Paldo to men legit!", platform: "Facebook" },
  { id: "33", name: "Paul", rating: 5, text: "Stay legit brooo!", platform: "Facebook" },
  { id: "34", name: "Eman", rating: 5, text: "Legit!", platform: "Facebook" },
  { id: "35", name: "Franz", rating: 5, text: "Legitt!", platform: "Facebook" },
  { id: "36", name: "John", rating: 5, text: "Trusted!", platform: "Facebook" },
  { id: "37", name: "Tyler", rating: 5, text: "Liget!", platform: "Facebook" },
  { id: "38", name: "Drew", rating: 5, text: "Legit dami kona nabili dito!", platform: "Facebook" },
  { id: "39", name: "Jovine", rating: 5, text: "L and Fast trans!", platform: "Facebook" },
  { id: "40", name: "Nix", rating: 5, text: "Legit!", platform: "Facebook" },
  { id: "41", name: "Edmark", rating: 5, text: "Fixed transaction two!", platform: "Facebook" },
  { id: "42", name: "Kyan", rating: 5, text: "Legit!", platform: "Facebook" },
  { id: "43", name: "Walter", rating: 5, text: "Legit!", platform: "Facebook" },
  { id: "44", name: "Walter", rating: 5, text: "Lrgit!", platform: "Facebook" },
  { id: "45", name: "Iverson", rating: 5, text: "Legit!", platform: "Facebook" },
  { id: "46", name: "Warren", rating: 5, text: "Legitt guysss sofeer!", platform: "Facebook" },
  { id: "47", name: "Mark", rating: 5, text: "Legitt 100 percent!", platform: "Facebook" },
  { id: "48", name: "Angelica", rating: 5, text: "LEGIT PA SA LEGITTT, the seller is still very kind :DD. Don't hesitate to buy!", platform: "Facebook" },
  { id: "49", name: "Andrei", rating: 5, text: "Legit!", platform: "Facebook" },
  { id: "50", name: "Jackilyn", rating: 5, text: "This is my second time ordering and I'll order again next timeeee super duper legit!", platform: "Facebook" },
  { id: "51", name: "Jjherik", rating: 5, text: "I buyed here two times and they never dissapoints!", platform: "Facebook" },
  { id: "52", name: "Merquin", rating: 5, text: "Legit tojj then kind to talk to!", platform: "Facebook" },
  { id: "53", name: "Dether", rating: 5, text: "Legit!", platform: "Facebook" },
  { id: "54", name: "Haiku", rating: 5, text: "Legit!", platform: "Facebook" },
  { id: "55", name: "Andrin", rating: 5, text: "2 times nako bumibili no scam to promise!", platform: "Facebook" },
  { id: "56", name: "Dela", rating: 5, text: "Legit!", platform: "Facebook" },
  { id: "57", name: "Sec", rating: 5, text: "Big L guys!", platform: "Facebook" },
  { id: "58", name: "Joshua", rating: 5, text: "Legit yan!", platform: "Facebook" },
  { id: "59", name: "Guile", rating: 5, text: "LEGIT PO GUYS NOT SCAM!", platform: "Facebook" },
  { id: "60", name: "Kiven", rating: 5, text: "Check mo chat ko boss!", platform: "Facebook" },
  { id: "61", name: "Jace", rating: 5, text: "Legit po thankyou bait pa!", platform: "Facebook" },
  { id: "62", name: "Raj", rating: 5, text: "Legit!", platform: "Facebook" },
  { id: "63", name: "Mark", rating: 5, text: "Legit!", platform: "Facebook" },
  { id: "64", name: "Jemarc", rating: 5, text: "Legit guys, get it now!", platform: "Facebook" },
  { id: "65", name: "Michael", rating: 5, text: "Super legit!", platform: "Facebook" },
  { id: "66", name: "Zed", rating: 5, text: "Legitt!", platform: "Facebook" },
  { id: "67", name: "Javy", rating: 5, text: "Legit seller!", platform: "Facebook" },
  { id: "68", name: "Kyen", rating: 5, text: "Super fast service, goods na goods!", platform: "Facebook" },
  { id: "69", name: "Christian", rating: 5, text: "Legitttt!", platform: "Facebook" },
  { id: "70", name: "Django", rating: 5, text: "Legit and fast transaction!", platform: "Facebook" },
  { id: "71", name: "Scoobie", rating: 5, text: "Big L para kay oma!", platform: "Facebook" },
  { id: "72", name: "Jèè", rating: 5, text: "3 times bili ko paldo paldo!", platform: "Facebook" },
  { id: "73", name: "Zed", rating: 5, text: "Legittt to!", platform: "Facebook" },
  { id: "74", name: "Mugiwara", rating: 5, text: "Legit!", platform: "Facebook" },
  { id: "75", name: "Cleoo", rating: 5, text: "Legit 200 pesos trans legit to the bosses!", platform: "Facebook" },
  { id: "76", name: "Cleoo", rating: 5, text: "Legit!", platform: "Facebook" },
  { id: "77", name: "Marco", rating: 5, text: "Legit...guysss!", platform: "Facebook" },
  { id: "78", name: "Lawritz", rating: 5, text: "Legit gaiis!", platform: "Facebook" },
  { id: "79", name: "Nya", rating: 5, text: "Legit 100% bilis ka transac!", platform: "Facebook" },
  { id: "80", name: "Rey", rating: 5, text: "Legit 100%!", platform: "Facebook" },
  { id: "81", name: "Patrick", rating: 5, text: "Legit!! Will do business again!", platform: "Facebook" },
  { id: "82", name: "Ramon", rating: 5, text: "Vouchh SMOOTH TRANSACTION thanks for creating a game passes poo!", platform: "Facebook" },
  { id: "83", name: "Carlo", rating: 5, text: "Legitttt!", platform: "Facebook" },
  { id: "84", name: "Jayrick", rating: 5, text: "Legit tysm via plus!", platform: "Facebook" },
  { id: "85", name: "Nel", rating: 5, text: "L 80 pesos!", platform: "Facebook" },
  { id: "86", name: "Plong", rating: 5, text: "Legit fast fast transaction!", platform: "Facebook" },
  { id: "87", name: "El", rating: 5, text: "Legit!", platform: "Facebook" },
  { id: "88", name: "Sebastian", rating: 5, text: "Up legit!", platform: "Facebook" },
  { id: "89", name: "Jed", rating: 5, text: "It's super legit and the process is really fast!", platform: "Facebook" },
  { id: "90", name: "Hajime", rating: 5, text: "First time buying in this store, the seller is kind they helped me to create another game just to have a gamepass. lol overall SUPER LEGIT!", platform: "Facebook" },
  { id: "91", name: "Kram", rating: 5, text: "Legit just bought it!", platform: "Facebook" },
  { id: "92", name: "Javy", rating: 5, text: "Legit!", platform: "Facebook" },
  { id: "93", name: "Johnpaul", rating: 5, text: "Legit fast transaction!", platform: "Facebook" },
  { id: "94", name: "Bagyo", rating: 5, text: "Liget tree game pass no scam mga tol!", platform: "Facebook" },
  { id: "95", name: "Bagyo", rating: 5, text: "Liget!", platform: "Facebook" },
  { id: "96", name: "Carl", rating: 5, text: "Legit!", platform: "Facebook" },
  { id: "97", name: "Hendrick", rating: 5, text: "Legit Seen moko yah bibile ako!", platform: "Facebook" },
  { id: "98", name: "Abdul", rating: 5, text: "Legit mga kuysss!", platform: "Facebook" },
  { id: "99", name: "Javann", rating: 5, text: "Legit!", platform: "Facebook" },
  { id: "100", name: "Forpya", rating: 5, text: "Legitt!", platform: "Facebook" },
  { id: "101", name: "Kian", rating: 5, text: "Legit po!", platform: "Facebook" },
  { id: "102", name: "Zairus", rating: 5, text: "Legittt!", platform: "Facebook" },
  { id: "103", name: "Zy", rating: 5, text: "Legittt!", platform: "Facebook" },
  { id: "104", name: "Yusoph", rating: 5, text: "Superr legitt!", platform: "Facebook" },
  { id: "105", name: "Glen", rating: 5, text: "Legit!", platform: "Facebook" },
  { id: "106", name: "Ysabelle", rating: 5, text: "Legit!! thank u so much!", platform: "Facebook" },
  { id: "107", name: "Keith", rating: 5, text: "Third time buyer, nalibre pa nga HAHAHA Thank you po!", platform: "Facebook" },
  { id: "108", name: "Charles", rating: 5, text: "Up up fast transac lang!", platform: "Facebook" },
  { id: "109", name: "Raven", rating: 5, text: "Legit BudgetWise Discounted Game Market 100%!", platform: "Facebook" },
  { id: "110", name: "Xian", rating: 5, text: "Legit toh solid!", platform: "Facebook" },
  { id: "111", name: "Jamier", rating: 5, text: "Legit, thank you very much, my purchase increased HAHA!", platform: "Facebook" },
  { id: "112", name: "Jackilyn", rating: 5, text: "Superrrr legit and trustworthy!", platform: "Facebook" },
  { id: "113", name: "Nick", rating: 5, text: "Legittt!", platform: "Facebook" },
  { id: "114", name: "Jhun", rating: 5, text: "Super legit and very fast trasaction!", platform: "Facebook" },
  { id: "115", name: "Sheena", rating: 5, text: "Bilis paden!", platform: "Facebook" },
  { id: "116", name: "Androw", rating: 5, text: "Legit!", platform: "Facebook" },
  { id: "117", name: "Dionne", rating: 5, text: "Legit!", platform: "Facebook" },
  { id: "118", name: "Beverly", rating: 5, text: "The seller is accommodating and legit. Fast and smooth transaction. Thank you!", platform: "Facebook" },
  { id: "119", name: "Zybelle", rating: 5, text: "Legit!", platform: "Facebook" },
  { id: "120", name: "Troy", rating: 5, text: "Legit guys bili na kayo!", platform: "Facebook" },
  { id: "121", name: "Nicole", rating: 5, text: "Fast transac! ty po!", platform: "Facebook" },
  { id: "122", name: "Gian", rating: 5, text: "Legit mga boss!", platform: "Facebook" },
  { id: "123", name: "Davidson", rating: 5, text: "Legit na legit!", platform: "Facebook" },
  { id: "124", name: "Arjuna", rating: 5, text: "Legit!! Fast transaction, thank you po!", platform: "Facebook" },
  { id: "125", name: "Jane", rating: 5, text: "The most legit one I've ever bought, I thought at first I would block them, but they're legit and so kind paaaaa!", platform: "Facebook" },
  { id: "126", name: "Jamier", rating: 5, text: "Liget guys our transaction is super fast!", platform: "Facebook" },
  { id: "127", name: "Xian", rating: 5, text: "This is super legit and trusted!", platform: "Facebook" },
  { id: "128", name: "Ruii", rating: 5, text: "Super legit and very fast transac!", platform: "Facebook" },
  { id: "129", name: "Daren", rating: 5, text: "Legit fast transact!", platform: "Facebook" },
  { id: "130", name: "Wowie", rating: 5, text: "I bought a few, legit!", platform: "Facebook" },
  { id: "131", name: "Francis", rating: 5, text: "This is Trustworthy, he gave the service that you were looking for!", platform: "Facebook" },
  { id: "132", name: "Sta", rating: 5, text: "Very legit!", platform: "Facebook" },
  { id: "133", name: "Dionne", rating: 5, text: "Vouched!", platform: "Facebook" },
  { id: "134", name: "Clarence", rating: 5, text: "LEGIT!", platform: "Facebook" },
  { id: "135", name: "Asher", rating: 5, text: "The seller is legit and kind!", platform: "Facebook" },
  { id: "136", name: "Jansen", rating: 5, text: "Legit dito mga kopal!", platform: "Facebook" },
  { id: "137", name: "Jethro", rating: 5, text: "Bilis ng transac legit!", platform: "Facebook" },
  { id: "138", name: "Aj", rating: 5, text: "Legit!", platform: "Facebook" },
  { id: "139", name: "Daniel", rating: 5, text: "LEGITT!", platform: "Facebook" },
  { id: "140", name: "Angel", rating: 5, text: "Thank you so much for fast and legit transaction!", platform: "Facebook" },
  { id: "141", name: "Arjuna", rating: 5, text: "Vouched thank you!", platform: "Facebook" },
  { id: "142", name: "Nonoy", rating: 5, text: "Supper liget!", platform: "Facebook" },
  { id: "143", name: "Mel", rating: 5, text: "Legittttttttttt.", platform: "Facebook" },
  { id: "144", name: "Keyaan", rating: 5, text: "Legitt guys omagad!", platform: "Facebook" },
  { id: "145", name: "Lou", rating: 5, text: "Legit po fast transaction!", platform: "Facebook" },
  { id: "146", name: "Ahron", rating: 5, text: "Legit, i will buy again lol!", platform: "Facebook" },
  { id: "147", name: "Jai", rating: 5, text: "This is my second time with you, you're so smooth boss!! thank you!", platform: "Facebook" },
  { id: "148", name: "Shane", rating: 5, text: "LEGITTT! I'll buy again next time!", platform: "Facebook" },
  { id: "149", name: "Jay", rating: 5, text: "TYSM, legit. Fast transaction and fast reply too, unlike other shops, so buy now!", platform: "Facebook" },
  { id: "150", name: "Jorence", rating: 5, text: "Legit!", platform: "Facebook" },
  { id: "151", name: "Vince", rating: 5, text: "Legeit 2nd time buying!", platform: "Facebook" },
  { id: "152", name: "Mel", rating: 5, text: "Legit, fast transac tyyy!", platform: "Facebook" },
  { id: "153", name: "Niño", rating: 5, text: "Legit po fast transaction!", platform: "Facebook" },
  { id: "154", name: "Jonnel", rating: 5, text: "Legit po!", platform: "Facebook" },
  { id: "155", name: "Prince", rating: 5, text: "Up legit!", platform: "Facebook" },
  { id: "156", name: "Kl", rating: 5, text: "I don't know how many purchases I bought HAHAHA still fast transaction!", platform: "Facebook" },
  { id: "157", name: "Rhainxe", rating: 5, text: "Legit kaka bili ko lang ule HAHAHAHAH!", platform: "Facebook" },
  { id: "158", name: "Rj", rating: 5, text: "Legit po!", platform: "Facebook" },
  { id: "159", name: "Les", rating: 5, text: "Legit!", platform: "Facebook" },
  { id: "160", name: "Nami", rating: 5, text: "Legit so much!", platform: "Facebook" },
  { id: "161", name: "Aeia", rating: 5, text: "Legit guyss!", platform: "Facebook" },
  { id: "162", name: "Harryl", rating: 5, text: "Legit!", platform: "Facebook" },
  { id: "163", name: "Cris", rating: 5, text: "Legit seller!", platform: "Facebook" },
  { id: "164", name: "Nyle", rating: 5, text: "Legit did second trans with bw bought another rainbow carpet thank youuuuu!", platform: "Facebook" },
  { id: "165", name: "Dan", rating: 5, text: "3rd purchase ty!", platform: "Facebook" },
  { id: "166", name: "Zhen", rating: 5, text: "Very legit po!", platform: "Facebook" },
  { id: "167", name: "Shanneon", rating: 5, text: "Legit yan, guys!", platform: "Facebook" },
  { id: "168", name: "Seraphine", rating: 5, text: "Legit!", platform: "Facebook" },
  { id: "169", name: "Ran", rating: 5, text: "Legit!", platform: "Facebook" },
  { id: "170", name: "Sid", rating: 5, text: "W GUYS BUY NAKAYO HWHWBW!", platform: "Facebook" },
  { id: "171", name: "Marky", rating: 5, text: "Legit!", platform: "Facebook" },
  { id: "172", name: "Dwane", rating: 5, text: "Legit!", platform: "Facebook" },
  { id: "173", name: "Chazz", rating: 5, text: "Another successful transactions!", platform: "Facebook" },
  { id: "174", name: "Kris", rating: 5, text: "Vouch!", platform: "Facebook" },
  { id: "175", name: "Chazz", rating: 5, text: "Legit!", platform: "Facebook" },
  { id: "176", name: "Dan", rating: 5, text: "Vouched!", platform: "Facebook" },
  { id: "177", name: "Thyron", rating: 5, text: "Legit!", platform: "Facebook" },
  { id: "178", name: "Carl", rating: 5, text: "Solid w yung process smooth transition lang. SALAMAT!", platform: "Facebook" },
  { id: "179", name: "Jimmy", rating: 5, text: "Legit Tnx.", platform: "Facebook" },
  { id: "180", name: "Heron", rating: 5, text: "Super liget!", platform: "Facebook" },
  { id: "181", name: "Kenwit", rating: 5, text: "This is legit and fast transaction! Thank you seller!", platform: "Facebook" },
  { id: "182", name: "Chu", rating: 5, text: "SUPER LEGIT!", platform: "Facebook" },
  { id: "183", name: "Wowie", rating: 5, text: "Legit na, mura pa!", platform: "Facebook" },
  { id: "184", name: "Harley", rating: 5, text: "Legit!", platform: "Facebook" },
  { id: "185", name: "Dwane", rating: 5, text: "Legitt sec transac fast transac!", platform: "Facebook" },
  { id: "186", name: "Josue", rating: 5, text: "100% legit, fast transaction!", platform: "Facebook" },
  { id: "187", name: "Earl", rating: 5, text: "Legit!! Trustworthy!", platform: "Facebook" },
  { id: "188", name: "Christian", rating: 5, text: "Legit!", platform: "Facebook" },
  { id: "189", name: "Axell", rating: 5, text: "Success+1 Legit!", platform: "Facebook" },
  { id: "190", name: "Corsinie", rating: 5, text: "Legitt ty!", platform: "Facebook" },
  { id: "191", name: "Chase", rating: 5, text: "Legit po!", platform: "Facebook" },
  { id: "192", name: "Justin", rating: 5, text: "Legit!! Fast transac!", platform: "Facebook" },
  { id: "193", name: "Raven", rating: 5, text: "Legit seller 100!", platform: "Facebook" },
  { id: "194", name: "Earl", rating: 5, text: "Legit smooth and fast transaction.", platform: "Facebook" },
  { id: "195", name: "Reynaldo", rating: 5, text: "Legit, 100 %!", platform: "Facebook" },
  { id: "196", name: "Jhaycee", rating: 5, text: "Legit!", platform: "Facebook" },
  { id: "197", name: "Sabian", rating: 5, text: "Legit! i will buy ulit soon HEHEHE!", platform: "Facebook" },
  { id: "198", name: "Justine", rating: 5, text: "Legit!", platform: "Facebook" },
  { id: "199", name: "Sai", rating: 5, text: "Another fast transactions thankyouu!", platform: "Facebook" },
  { id: "200", name: "Lloyd", rating: 5, text: "2nd time buyer very legit!", platform: "Facebook" },
  { id: "201", name: "Kristian", rating: 5, text: "Legittt!", platform: "Facebook" },
  { id: "202", name: "Menx", rating: 5, text: "L FAST TRANS PA!", platform: "Facebook" },
  { id: "203", name: "Lloyd", rating: 5, text: "Thank you legit!", platform: "Facebook" },
  { id: "204", name: "Choline", rating: 5, text: "First time buying, success, legit tong market nato fast transac din!", platform: "Facebook" },
  { id: "205", name: "Ethan", rating: 5, text: "Legit to the legit and fast in inquiries!", platform: "Facebook" },
  { id: "206", name: "Tarcila", rating: 5, text: "Legit!", platform: "Facebook" },
  { id: "207", name: "Mohaizin", rating: 5, text: "Legitt 100% fast transaction!", platform: "Facebook" },
  { id: "208", name: "Nash", rating: 5, text: "Legit and fast reply, your partner should be like that too!", platform: "Facebook" },
  { id: "209", name: "Glaivin", rating: 5, text: "Legit po, super sulit!", platform: "Facebook" },
  { id: "210", name: "Keith", rating: 5, text: "Legit! Second time buyerrr!", platform: "Facebook" },
  { id: "211", name: "Vry", rating: 5, text: "Legit to guys!", platform: "Facebook" },
  { id: "212", name: "Steven", rating: 5, text: "Solid super legit fast transac!", platform: "Facebook" },
  { id: "213", name: "Vince", rating: 5, text: "Legit!", platform: "Facebook" },
  { id: "214", name: "Jethro", rating: 5, text: "LEGITTTT!", platform: "Facebook" },
  { id: "215", name: "Charles", rating: 5, text: "Legit po very legit!", platform: "Facebook" },
  { id: "216", name: "Luis", rating: 5, text: "Legittt!", platform: "Facebook" },
  { id: "217", name: "Zami", rating: 5, text: "Legit super solid transaction here you go!", platform: "Facebook" },
  { id: "218", name: "Zami", rating: 5, text: "Legit tysm!", platform: "Facebook" },
  { id: "219", name: "Aleiza", rating: 5, text: "W seller, tysm sa service!", platform: "Facebook" },
  { id: "220", name: "Kl", rating: 5, text: "Solid ambilis transac!", platform: "Facebook" },
  { id: "221", name: "Kerido", rating: 5, text: "Legit! Sobra!", platform: "Facebook" },
  { id: "222", name: "Sai", rating: 5, text: "Another buy super L thankyouuu!", platform: "Facebook" },
  { id: "223", name: "Sheena", rating: 5, text: "Solid bilis lang!", platform: "Facebook" },
  { id: "224", name: "Dale", rating: 5, text: "Another smooth transaction with this shop! Thank you so much for a smooth and fast transactio!", platform: "Facebook" },
  { id: "225", name: "Prince", rating: 5, text: "Legit tysm po!", platform: "Facebook" },
  { id: "226", name: "Cri", rating: 5, text: "Uppp Legit!", platform: "Facebook" },
  { id: "227", name: "Amiel", rating: 5, text: "Legit! 2x buyer!", platform: "Facebook" },
  { id: "228", name: "Ken", rating: 5, text: "2nd purchase super legit!", platform: "Facebook" },
  { id: "229", name: "Dale", rating: 5, text: "Legit as always! super smooth and fast transaction!", platform: "Facebook" },
  { id: "230", name: "Mik", rating: 5, text: "Superrr legittt!", platform: "Facebook" },
  { id: "231", name: "Kirj", rating: 5, text: "Fast and legit, super recommended!", platform: "Facebook" },
  { id: "232", name: "Amiel", rating: 5, text: "Legit!", platform: "Facebook" },
  { id: "233", name: "Luis", rating: 5, text: "Legitt!", platform: "Facebook" },
  { id: "234", name: "Kent", rating: 5, text: "W, legit good at handling customers!", platform: "Facebook" },
  { id: "235", name: "Mohaizin", rating: 5, text: "Legit!", platform: "Facebook" },
  { id: "236", name: "Gabriel", rating: 5, text: "Legit talaga second purchase kuna!", platform: "Facebook" },
  { id: "237", name: "Karina", rating: 5, text: "Legit po!! tysm sa guide!", platform: "Facebook" },
  { id: "238", name: "Kian", rating: 5, text: "Legit!", platform: "Facebook" },
  { id: "239", name: "Jhon", rating: 5, text: "Super legit 100%!", platform: "Facebook" },
  { id: "240", name: "Emerson", rating: 5, text: "Legit, thank you!", platform: "Facebook" },
  { id: "241", name: "Rolan", rating: 5, text: "LEGIT RECOMMEND!", platform: "Facebook" },
  { id: "242", name: "Nanah", rating: 5, text: "LEGIT approachable and mabait pa.", platform: "Facebook" },
  { id: "243", name: "Gabriel", rating: 5, text: "Up legit 100%!", platform: "Facebook" },
  { id: "244", name: "Mik", rating: 5, text: "Legitttt!", platform: "Facebook" },
  { id: "245", name: "Kenshin", rating: 5, text: "Legit guys!", platform: "Facebook" },
  { id: "246", name: "Drew", rating: 5, text: "We have 3 transactions already!", platform: "Facebook" },
  { id: "247", name: "Christopher", rating: 5, text: "Legit grabi!", platform: "Facebook" },
  { id: "248", name: "Patrick", rating: 5, text: "Legit Recommend!", platform: "Facebook" },
  { id: "249", name: "Precious", rating: 5, text: "Legit!", platform: "Facebook" },
  { id: "250", name: "Lucas", rating: 5, text: "Legitimate!", platform: "Facebook" },
  { id: "251", name: "Johnlord", rating: 5, text: "Legit guys, I bought three gamepasses on cdid, they're legit guys.", platform: "Facebook" },
  { id: "252", name: "Gery", rating: 5, text: "Legit!", platform: "Facebook" },
  { id: "253", name: "Ben", rating: 5, text: "I've bought two extreme legit soliddd!", platform: "Facebook" },
  { id: "254", name: "Jhomerlee", rating: 5, text: "Super super legittttt!", platform: "Facebook" },
  { id: "255", name: "Jhomerlee", rating: 5, text: "Legit!", platform: "Facebook" },
  { id: "256", name: "Sebastian", rating: 5, text: "Super L!", platform: "Facebook" },
  { id: "257", name: "Doyle", rating: 5, text: "Legittt, I'm getting annoyed!", platform: "Facebook" },
  { id: "258", name: "Doyle", rating: 5, text: "Legitt!", platform: "Facebook" },
  { id: "259", name: "Vahn", rating: 5, text: "Legit to guys proven and tested!", platform: "Facebook" },
  { id: "260", name: "Khade", rating: 5, text: "Legit tysm idol!", platform: "Facebook" },
  { id: "261", name: "Niño", rating: 5, text: "Legit!", platform: "Facebook" },
  { id: "262", name: "Tai", rating: 5, text: "Legit guys!", platform: "Facebook" },
  { id: "263", name: "Nathan", rating: 5, text: "Legit!", platform: "Facebook" },
  { id: "264", name: "Daniel", rating: 5, text: "You guys buy here it's legit legit faster than your mom!", platform: "Facebook" },
  { id: "265", name: "Ma", rating: 5, text: "100% legit po!", platform: "Facebook" },
  { id: "266", name: "Triman", rating: 5, text: "LEGIT DITO PROMISE!", platform: "Facebook" },
];

export const reviews: Review[] = rawReviews.filter((review) =>
  isGenuineReview(review.text),
);
